services:
  # =========================
  # Postgres (API DB)
  # =========================
  db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  # Corre migraciones antes de levantar la API
  migrator:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: ["npx", "prisma", "migrate", "deploy"]
    restart: "no"

  # =========================
  # Mongo (Logs DB)
  # =========================
  mongo-logs:
    image: mongo:7
    container_name: mongo-logs
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_logs_data:/data/db

  # =========================
  # Logs Service
  # =========================
  logs-service:
    build:
      context: ../corpoturismo-logs-service
      dockerfile: Dockerfile
    container_name: logs-service
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 4010

      MONGO_URL: mongodb://mongo-logs:27017
      MONGO_DB: corpoturismo_db_logs

      INGEST_API_KEY: ${LOGS_INGEST_API_KEY}
      READ_API_KEY: ${LOGS_READ_API_KEY}
    ports:
      - "4010:4010"
    depends_on:
      mongo-logs:
        condition: service_started

  # =========================
  # API
  # =========================
  api:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
      logs-service:
        condition: service_started
    ports:
      - "3000:3000"
    environment:
      # Asegura conexión al logs-service dentro de la red docker
      LOGS_SERVICE_URL: http://logs-service:4010

volumes:
  pgdata: {}
  mongo_logs_data: {}